language: python
python:
  - "2.7"
  - "3.6"

env:
  - SPHINX_VERSION=1.6.0
  - SPHINX_VERSION=1.7.0
  - SPHINX_VERSION=dev

install:
  - pip install coveralls
  - pip install -q Sphinx~=$SPHINX_VERSION
  - python setup.py install

script:
  - coverage run --source=classycode --omit="*/tests/*.py" setup.py test

after_success:
  - coveralls
